# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

name: $(TeamProject)..$(Build.DefinitionName)..$(SourceBranchName)..$(Date:yyyyMMdd)$(Rev:.r)

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '000ch01and02rg-sp'
    subscriptionId: $(subscription_ID)
    action: 'Create Or Update Resource Group'
    resourceGroupName: '000ch01and02rg'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/JimBlizzard/hack-iac/trunk/arm-templates/ch01-02-simple/azuredeploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/JimBlizzard/hack-iac/trunk/arm-templates/ch01-02-simple/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'