# kv-for-pipeline-secrets.yml 

# Note: The Key Vault is located in RG: 000iac-kv-rg, KV: kv-for-iac


trigger:
- none
    
pool:
  vmImage: 'ubuntu-latest'
    
name: $(TeamProject)..$(Build.DefinitionName)..$(SourceBranchName)..$(Date:yyyyMMdd)$(Rev:.r)
    
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
    
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'kv-for-iac-sp'
    KeyVaultName: 'kv-for-iac'
    SecretsFilter: '*'
    RunAsPreJob: false

- script: echo $(subscriptionID) > secret.txt
  # Note: the $(subscriptionID) variable os pulled from the Key Vault

- publish: secret.txt
  